database:
    host: localhost
    port: 5432
    name: maurodatamapper_hs6
---
apiUser:
    username: admin@maurodatamapper.com
    password: password
---
#Default for plugins/applications
---
maurodatamapper:
    security:
        public: false
    authority:
        name: 'Mauro Data Mapper'
        url: http://localhost
    email:
        from:
            address: 'mtf@maurodatamapper.com'
grails:
    profile: rest-api
    codegen:
        defaultPackage: uk.ac.ox.softeng.maurodatamapper.testing.functional
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
        failOnError: true
    resources:
        pattern: /**
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'

# Spring Actuator Endpoints are Disabled by Default
management:
    endpoints:
        enabled-by-default: false
        web:
            exposure:
                include:
                    - 'health'
                    - 'shutdown'
        jmx:
            exposure:
                include: '*'
    endpoint:
        shutdown:
            enabled: true
        health:
            enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
                - application/json
                - text/json
            hal:
                - application/hal+json
                - application/hal+xml
            xml:
                - text/xml
                - application/xml
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    exceptionresolver:
        params:
            exclude:
                - password
                - tempPassword
    cors:
        enabled: true
        # The following are the defaults
        allowedOrigins: ['*']
        allowedMethods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'HEAD']
        allowedHeaders: [ 'origin', 'content-type', 'accept', 'authorization', 'pragma', 'cache-control' ]
        #exposedHeaders: null
        #maxAge: 1800
        #allowCredentials: true
    views:
        markup:
            autoEscape: true
            prettyPrint: false
            autoIndent: false
            autoNewLine: false
    databinding:
        dateFormats:
            - "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"
            - "yyyy-MM-dd'T'HH:mm:ss.SSXXX"
            - "yyyy-MM-dd'T'HH:mm:ss.SXXX"
            - "yyyy-MM-dd'T'HH:mm:ssXXX"
            - 'yyyy-MM-dd HH:mm:ss.S'
            - "yyyy-MM-dd'T'HH:mm:ss'Z'"
            - "yyyy-MM-dd HH:mm:ss.S z"
            - "yyyy-MM-dd"
---
hibernate:
    search:
        default.indexBase: '/tmp/lucene/testing/functional'
#    generate_statistics: true

---
dataSource:
    pooled: true
    jmxExport: true
    formatSql: true
---
environments:
    test:
        spring.flyway.enabled: false
        database:
            name: 'mtf'
            creation: 'CREATE SCHEMA IF NOT EXISTS CORE\;CREATE SCHEMA IF NOT EXISTS SECURITY\;CREATE SCHEMA IF NOT EXISTS DATAMODEL\;CREATE SCHEMA IF NOT EXISTS TERMINOLOGY\;CREATE SCHEMA IF NOT EXISTS DATAFLOW\;CREATE SCHEMA IF NOT EXISTS REFERENCEDATA\;CREATE SCHEMA IF NOT EXISTS FEDERATION'
        dataSource:
            driverClassName: org.h2.Driver
            dialect: org.hibernate.dialect.H2Dialect
            username: sa
            password: ''
            dbCreate: create
            url: 'jdbc:h2:mem:${database.name};LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;INIT=${database.creation}'
    development:
        dataSource:
            driverClassName: org.postgresql.Driver
            dialect: org.hibernate.dialect.PostgreSQL10Dialect
            username: maurodatamapper
            password: MauroDataMapper1234
            dbCreate: none
            url: 'jdbc:postgresql://${database.host}:${database.port}/${database.name}'
    production:
        dataSource:
            driverClassName: org.postgresql.Driver
            dialect: org.hibernate.dialect.PostgreSQL10Dialect
            username: maurodatamapper
            password: MauroDataMapper1234
            dbCreate: none
            url: 'jdbc:postgresql://${database.host}:${database.port}/${database.name}'
---
